### ISSUE TITLE
Fetching multiple symbols broken

### ISSUE THREAD

**Issue by slavasav** [innes213/pyhoofinance#3]
Hi,
Starting from last week pyhoofinance seems to be broken when fetching multiple symbols:
{'day_low': None, 'error_indication': 'N/A', 'name': 'N/A', 'average_daily_volume': 358041.0, 'symbol': 'N/A', 'volume': None, 'last_trade_price_only': 154.5, 'day_high': None, 'open': None, 'change': -0.8}
(Although some data is fetched)

**Comment by innes213** [comment]
Apologies for my late response. I will fix this in the next few days.

**Comment by slavasav** [comment]
Thanks! Slava 14.04.2015, 09:30, "Rob Innes Hislop" notifications@github.com:Apologies for my late response. I will fix this in the next few days.—Reply to this email directly or view it on GitHub.

**Comment by innes213** [comment]
Yahoo has changed their API after years of leaving it unchanged. Looks like they really cleaned house and removed some redundant tokens. pyhoofinance was using some of these so some fields (like `name` and `ticker_symbol` need to be remapped. No big deal. I should have a new package out this weekend. Thanks again!

**Comment by innes213** [comment]
Changes made, package posted on PYPI. Versioned as v0.2.0. Depending on the number of symbols being requested, this package is 5 times faster than previous releases.

**Comment by slavasav** [comment]
Thanks a lot, it's the fastest yahoo module for loading lots of tickers at once.
There is one minor issue with installation using pip, it complains about missing setup.py.
